### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by lgandecki** [Kegsay/ProbablyFlowTyped#1]
Hey man!
I and my team would love to help with this project.
Please let me know when you have some time to chat.

What timezone are you in? We are in CET +1.

**Comment by Kegsay** [comment]
GMT :)

Some help would be most appreciated. I've got the core building blocks in place:
 - Test runner
 - CLI
 - AST parsing
 - Basic ability to modify nodes in the AST

I'm having issues getting decent Flow definition files to test against. The Flow definitions can look quite different and assert more things, but that means I can't use them when asserting generator output. For example, see the [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/deep-diff/deep-diff.d.ts) vs [that](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/deep-diff_v0.3.x/flow_v0.27.x-/deep-diff_v0.3.x.js) - I can't possibly automate setting the `kind` to the values listed in the Flow definition.

It would be most helpful if there were "realistic" versions of the flow definitions which a machine could reasonably produce. It's hard enough getting the generator working, let alone hand-crafting flow definitions to test against: so any PRs with the `.d.ts` and corresponding hand-crafted `.js.flow` which is confirmed working would be **wonderful**.

**Comment by suprsankr** [comment]
Hi. 
I used this package to generate flow lib definitions from a d.ts file. When i run 'flow check', i get these errors from the new flow libdef files: 
 19:   export interface InterfaceDefinition extends Object{
       ^^^^^^ Library parse error:
 19:   export interface InterfaceDefinition extends Object{
       ^^^^^^ Unexpected token export

The page here-https://flowtype.org/docs/third-party.html#_ mentions that we need to have a 
declare module "name.." {
  declare module.exports: {
   someMethod<T>(params): returnType;
  }
}

But the libdefs generated with this package look different. I am not sure how to make flow accept the generated lib defs ? 

I put the generated libdefs under a /customlibs folder (in the project root) and gave
[libs]
/customlibs/
 in the .flowconfig

**Comment by Kegsay** [comment]
This project in its current form barely works for simple `.d.ts` files. It's a huge WIP at the moment.

**Comment by Kegsay** [comment]
I'm deprecating this project so the community can focus on a single converter project and not multiple. https://github.com/joarwilk/typedef-converter is currently more comprehensive.
