### ISSUE TITLE
Support for @flow to .d.ts

### ISSUE THREAD

**Issue by DxCx** [Kegsay/ProbablyFlowTyped#2]
Hi,

Can you add support for the opposite direction?
Converting javascript files with @flow into d.ts files?

**Comment by Kegsay** [comment]
I have no plans to add this in the short-medium term. We don't even have .d.ts -> flow working yet :)

**Comment by DxCx** [comment]
have you tried doing it and encountered issues?
or you mean that you don't have the need...?

**Comment by Kegsay** [comment]
I'm deprecating this project so the community can focus on a single converter project and not multiple. https://github.com/joarwilk/typedef-converter is currently more comprehensive.
